name: "workflow: build and test"

on:
  workflow_call:
    inputs:
      elixir-version:
        required: false
        type: string
        default: "1.14.4"
      otp-version:
        required: false
        type: string
        default: "26.0"

    # secrets:
    #   CODECOV_TOKEN:
    #     required: true

env:
  MIX_ENV: test
  DATABASE_PORT: 5432
  DATABASE_HOST: localhost
  DATABASE_NAME: surf_marketplace
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres

jobs:
  run:
    name: " "
    services:
      db:
        image: postgis/postgis:13-3.1
        env:
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          POSTGRES_USER: ${{ env.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ inputs.elixir-version }}
          otp-version: ${{ inputs.otp-version }}
          build-flags: --all-warnings --warnings-as-errors

      - name: Run Tests
        # run: mix coveralls.json --warnings-as-errors
        run: mix test --warnings-as-errors
        if: always()

      # Codecov bot will comment on the PR with per-file coverage deltas.
      # - name: Upload to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     # fail_ci_if_error: true
      #     fail_ci_if_error: false
      #     files: ./cover/excoveralls.json
      #     token: ${{ secrets.CODECOV_TOKEN }}
