name: "workflow: deploy to fly.io"

on:
  workflow_call:
    secrets:
      FLY_API_TOKEN:
        required: true

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: basilenouvellet
  DOCKER_IMAGE: ghcr.io/basilenouvellet/surf_marketplace:main

jobs:
  run:
    name: " "
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.0.541

      - name: Flyctl version
        run: flyctl version

      # NOTE: Cannot make Flyctl authenticate with ghcr registry for some reason...
      #       We have to pull the image locally manually.
      - name: Pull Docker image
        run: docker pull ${{ env.DOCKER_IMAGE }}

      - name: Deploy to fly.io
        run: flyctl deploy --local-only --image ${{ env.DOCKER_IMAGE }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
