name: "workflow: type linting"

on:
  workflow_call:
    inputs:
      elixir-version:
        required: false
        type: string
        default: "1.14.4"
      otp-version:
        required: false
        type: string
        default: "26.0"

env:
  MIX_ENV: dev
  CACHE_KEY: v2

jobs:
  run:
    name: " "
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ inputs.elixir-version }}
          otp-version: ${{ inputs.otp-version }}

      # Don't cache PLTs based on mix.lock hash, as Dialyzer can incrementally update even old ones.
      # Cache key based on Elixir & Erlang version.
      - name: Restore PLT cache
        uses: actions/cache@v3
        id: plt-cache
        with:
          path: priv/plts/
          key: plt-${{ env.CACHE_KEY }}-${{ runner.os }}-${{ inputs.elixir-version }}-${{ inputs.otp-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plt-${{ env.CACHE_KEY }}-${{ runner.os }}-${{ inputs.elixir-version }}-${{ inputs.otp-version }}

      # Create PLTs if no cache was found.
      # (If they were cached at all, they'll be updated when we run mix dialyzer with no flags.)
      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer --format github
